# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created on')),
                ('author', models.CharField(max_length=128, verbose_name='Author username')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogEntry')),
            ],
        ),
    ]
